### ISSUE TITLE
The abstract is "replace boilerplate"

### ISSUE THREAD

**Issue by robrwo** [trwyant/perl-Game-Life-Faster#1]
In `Build.PL`:
```perl
 dist_abstract => '<<< replace boilerplate >>>'
```
I assume this is used for generating `Makefile.PL`, the `META.yml` and `META.json` files. It shows up in the CPAN index as "replace boilderplate".

**Comment by trwyant** [comment]
Oooops! Thank you very much for bringing this to my attention. Fixed, I certainly hope.
